Add an unit test to reproduce the panick caused by huge value size
$ go test -run TestDB_HugeValue -v
seed: 44000
quick settings: count=5, items=1000, ksize=1024, vsize=1024
=== RUN   TestDB_HugeValue
--- FAIL: TestDB_HugeValue (0.06s)
panic: runtime error: slice bounds out of range [::268435459] with length 268435455 [recovered]
	panic: runtime error: slice bounds out of range [::268435459] with length 268435455

goroutine 7 [running]:
testing.tRunner.func1.2({0x1031ae420, 0x14000016090})
	/Users/wachao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.3.darwin-arm64/src/testing/testing.go:1734 +0x1ac
testing.tRunner.func1()
	/Users/wachao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.3.darwin-arm64/src/testing/testing.go:1737 +0x334
panic({0x1031ae420?, 0x14000016090?})
	/Users/wachao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.3.darwin-arm64/src/runtime/panic.go:792 +0x124
go.etcd.io/bbolt/internal/common.UnsafeByteSlice(...)
	/Users/wachao/go/src/github.com/ahrtr/bbolt/internal/common/unsafe.go:26
go.etcd.io/bbolt/internal/common.WriteInodeToPage({0x14000104f80?, 0x1, 0x4?}, 0x14010210000)
	/Users/wachao/go/src/github.com/ahrtr/bbolt/internal/common/inode.go:81 +0x288
go.etcd.io/bbolt.(*node).write(0x1400017a000?, 0x4001?)
	/Users/wachao/go/src/github.com/ahrtr/bbolt/node.go:199 +0xa0
go.etcd.io/bbolt.(*node).spill(0x1400014e0e0)
	/Users/wachao/go/src/github.com/ahrtr/bbolt/node.go:334 +0x1dc
go.etcd.io/bbolt.(*Bucket).spill(0x14000104f40)
	/Users/wachao/go/src/github.com/ahrtr/bbolt/bucket.go:786 +0x278
go.etcd.io/bbolt.(*Bucket).spill(0x1400017a018)
	/Users/wachao/go/src/github.com/ahrtr/bbolt/bucket.go:753 +0xc0
go.etcd.io/bbolt.(*Tx).Commit(0x1400017a000)
	/Users/wachao/go/src/github.com/ahrtr/bbolt/tx.go:204 +0x260
go.etcd.io/bbolt.(*DB).Update(0x1031cdf90?, 0x1400007cf28)
	/Users/wachao/go/src/github.com/ahrtr/bbolt/db.go:922 +0xc4
go.etcd.io/bbolt_test.TestDB_HugeValue(0x14000003c00)
	/Users/wachao/go/src/github.com/ahrtr/bbolt/db_test.go:1560 +0x110
testing.tRunner(0x14000003c00, 0x1031c9ef0)
	/Users/wachao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.3.darwin-arm64/src/testing/testing.go:1792 +0xe4
created by testing.(*T).Run in goroutine 1
	/Users/wachao/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.3.darwin-arm64/src/testing/testing.go:1851 +0x374
exit status 2
FAIL	go.etcd.io/bbolt	0.285s

Signed-off-by: Benjamin Wang <benjamin.ahrtr@gmail.com>